# Simple workflow for deploying static content to GitHub Pages
name: Deploy to FTP

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  web-deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.4
      
    - name: Deploy commongroundsmarket.com
      uses: cinderblockgames/ftp-action@v1.2.2
      with:
        # required
        server: ${{ secrets.FTP_HOST }}
        username: ${{ secrets.FTP_USER }}
        password: ${{ secrets.FTP_PASS }}
        # optional
        port: ${{ secrets.FTP_PORT }}
        source: site
        destination: ${{ secrets.FTP_TARGET }}
        skipUnchanged: true
        skipDirectories: .github|.well-known|configs|private-keys
        test: false
